
/* --------------------------------------------------------------------
   Code generated by a SAS task
   
   Generated on Tuesday, May 16, 2023 at 7:35:57 AM
   By task:     Import Data Wizard
   
   Source file: D:\SASData\dua_052882\Sndbx\ming\hcc\hhs_hcc_table2.csv
   Server:      SASApp
   
   Output data: WORK.hhs_hcc_table2
   Server:      SASApp
   -------------------------------------------------------------------- */

DATA WORK.hhs_hcc_table2;
    LENGTH
        hcpcs_cd         $ 5
        desc             $ 28
        cy2019_f         $ 3
        cy2020_f         $ 3
        Footnote           8 ;
    LABEL
        hcpcs_cd         = "HCPCS/CPT Code"
        desc             = "Short Description"
        cy2019_f         = "In CY2019 Included List?"
        cy2020_f         = "In CY2020 Included List?" ;
    FORMAT
        hcpcs_cd         $CHAR5.
        desc             $CHAR28.
        cy2019_f         $CHAR3.
        cy2020_f         $CHAR3.
        Footnote         BEST1. ;
    INFORMAT
        hcpcs_cd         $CHAR5.
        desc             $CHAR28.
        cy2019_f         $CHAR3.
        cy2020_f         $CHAR3.
        Footnote         BEST1. ;
    INFILE 'W:\SASWork\_TD14084_SAS-PROD-1_\#LN00066'
        LRECL=45
        ENCODING="WLATIN1"
        TERMSTR=CRLF
        DLM='7F'x
        MISSOVER
        DSD ;
    INPUT
        hcpcs_cd         : $CHAR5.
        desc             : $CHAR28.
        cy2019_f         : $CHAR3.
        cy2020_f         : $CHAR3.
        Footnote         : ?? BEST1. ;
RUN;


